const formJson = {
  title: "Comprehensive Survey Form",
  fields: [
    {
      id: "first_name",
      label: "First Name",
      type: "text",
      required: true,
      minLength: 2,
      maxLength: 50,
    },
    {
      id: "last_name",
      label: "Last Name",
      type: "text",
      required: true,
      minLength: 2,
      maxLength: 50,
    },
    {
      id: "email",
      label: "Email Address",
      type: "email",
      required: true,
      pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
    },
    {
      id: "password",
      label: "Password",
      type: "password",
      required: true,
      minLength: 8,
    },
    {
      id: "phone",
      label: "Phone Number",
      type: "tel",
      pattern: "^[0-9]{10}$",
      required: true,
    },
    {
      id: "dob",
      label: "Date of Birth",
      type: "date",
      required: true,
    },
    {
      id: "appointment_time",
      label: "Preferred Appointment Time",
      type: "time",
      required: false,
    },
    {
      id: "age",
      label: "Age",
      type: "number",
      required: true,
      min: 1,
      max: 120,
    },
    {
      id: "color",
      label: "Favorite Color",
      type: "color",
      required: false,
    },
    {
      id: "gender",
      label: "Gender",
      type: "radio",
      options: [
        { label: "Male", value: "male" },
        { label: "Female", value: "female" },
        { label: "Non-binary", value: "nonbinary" },
        { label: "Other", value: "other" },
      ],
      required: true,
    },
    {
      id: "hobbies",
      label: "Hobbies",
      type: "checkbox",
      options: [
        { label: "Reading", value: "reading" },
        { label: "Traveling", value: "traveling" },
        { label: "Gaming", value: "gaming" },
        { label: "Sports", value: "sports" },
      ],
    },
    {
      id: "marital_status",
      label: "Marital Status",
      type: "select",
      required: true,
      options: [
        { label: "Single", value: "single" },
        { label: "Married", value: "married" },
        { label: "Divorced", value: "divorced" },
        { label: "Widowed", value: "widowed" },
      ],
    },
    {
      id: "bio",
      label: "Tell us about yourself",
      type: "textarea",
      required: false,
      maxLength: 500,
    },
    {
      id: "is_smoker",
      label: "Do you smoke?",
      type: "radio",
      options: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
      ],
      dependentQuestions: [
        {
          id: "smoking_frequency",
          label: "How often do you smoke?",
          type: "select",
          options: [
            { label: "Daily", value: "daily" },
            { label: "Occasionally", value: "occasionally" },
            { label: "Rarely", value: "rarely" },
          ],
          required: true,
        },
      ],
    },
    {
      id: "is_alcoholic",
      label: "Do you consume alcohol?",
      type: "radio",
      options: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
      ],
      dependentQuestions: [
        {
          id: "alcohol_frequency",
          label: "How often do you consume alcohol?",
          type: "select",
          options: [
            { label: "Daily", value: "daily" },
            { label: "Occasionally", value: "occasionally" },
            { label: "Rarely", value: "rarely" },
          ],
          required: true,
        },
      ],
    },
    {
      id: "consent",
      label: "I agree to the terms and conditions",
      type: "checkbox",
      required: true,
    },
    {
      id: "profile_picture",
      label: "Upload Profile Picture",
      type: "file",
      required: false,
    },
    {
      id: "website",
      label: "Personal Website",
      type: "url",
      required: false,
    },
  ],
};
